# Generated by Django 5.0.1 on 2024-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomphoto',
            field=models.ImageField(upload_to='C:/Users/seanj/Desktop/Hotel_Project/Hotel/images'),
        ),
    ]
