# Generated by Django 5.0.1 on 2024-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_room_roomphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomphoto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
