# Generated by Django 5.0.1 on 2024-01-20 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_bookings_delete_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='RoomBooking',
        ),
    ]
