# Generated by Django 5.0.1 on 2024-01-21 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_rename_bookings_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
