# Generated by Django 5.0.1 on 2024-01-21 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_roombooking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
