# Generated by Django 5.0.1 on 2024-01-22 10:29

import Hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_roombooking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_code',
            field=models.CharField(default=Hotel.models.generatebookingcode, editable=False, max_length=8, unique=True),
        ),
    ]
